name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Test on both Ubuntu and Windows

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: gameshop
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=1234"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Clear Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install Maven dependencies
      - name: Install dependencies
        run: mvn install -DskipTests

      # Run tests
      - name: Run tests
        env:
          DB_URL: jdbc:mysql://localhost:3306/gameshop
          DB_USER: root
          DB_PASSWORD: 1234
        run: mvn clean test -e -DskipTests=false

      # Save test results for inspection if tests fail
      - name: Store test results
        if: failure()  # only store if tests fail
        uses: actions/upload-artifact@v3  # updated to v3
        with:
          name: test-results
          path: target/surefire-reports/  # default Maven test result path
